### ISSUE TITLE
Add pre-trained model

### ISSUE THREAD

**Issue by Gaozhongpai** [federicopozzi33/MobileOne-PyTorch#2]
Can anyone add a pre-trained model for the MobileOne network?

**Comment by Gaozhongpai** [comment]
Thanks for this repo. It improve my 3D hand tracking 5 times faster than MobileNet-V3.
https://www.youtube.com/watch?v=np1FLNsd6qA&t=17s

**Comment by federicopozzi33** [comment]
> Can anyone add a pre-trained model for the MobileOne network?

I'm working on it!

> Thanks for this repo. It improve my 3D hand tracking 5 times faster than MobileNet-V3.
> https://www.youtube.com/watch?v=np1FLNsd6qA&t=17s

I'm very glad to hear that!
